version: "3.7"
services:
    database:
        image: ${DB_IMAGE}:${DB_VERSION}
        container_name: database
        volumes:
            - ./mysql:/var/lib/mysql
            - "./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf"
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        networks:
            - ${DOCKER_NETWORK}
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        depends_on:
            - database
        ports:
            - 4000:80
        environment:
            - PMA_HOST=database
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=500M
        networks:
            - ${DOCKER_NETWORK}

networks:
    backend:
        driver: bridge
